name: binar_flutter_json_serialization
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  json_annotation: ^4.7.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
